# Generated by Django 4.0.5 on 2022-06-25 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Введите номер телефона в формате +996 ХХХ ХХХ ХХХ', regex='^\\+[9]{2}?[6] [0-9]{3} [0-9]{3} [0-9]{3}$')], verbose_name='Номер телефона'),
        ),
    ]
