# Generated by Django 4.0.5 on 2022-06-25 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='photo',
            field=models.ImageField(null=True, upload_to='ad_photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
