# Generated by Django 4.0.5 on 2022-06-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_ad_photo_alter_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='piblished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
