# Generated by Django 4.0.5 on 2022-06-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_ad_piblished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ad_photos', verbose_name='Фото'),
        ),
    ]
