# Generated by Django 4.0.5 on 2022-06-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_ad_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='piblished_at',
            new_name='published_at',
        ),
    ]
